version: '3.3'
services:
  brakdagflask:
    build: .
    container_name: brakdagflask
    networks:
      - brakdag-network
    ports:
      - '8000:5000'
    expose:
      - '5000'
    image: 'brakdagflask:latest'
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${PWD}/mysqlcustom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    networks:
      - brakdag-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_BRAKDAG_PASS}
      MYSQL_DATABASE: brakdag
      MYSQL_USER: brakdag
      MYSQL_PASSWORD: ${DB_BRAKDAG_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - brakdag-network
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_BRAKDAG_PASS}
  newsparse:
    build:
      context: .
      dockerfile: newsparse/Dockerfile
    ports:
      - '3300:3300'
    expose:
      - '3300'
    environment:
      - PYTHONUNBUFFERED=0  
    networks:
      - brakdag-network
    container_name: newsparse
    restart: always
    image: 'newsparse:latest'
    depends_on:
      - brakdagflask
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
  swag:
    cap_add:
      - NET_ADMIN
    container_name: swag
    networks:
      - brakdag-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=brakdag.nl
      - SUBDOMAINS=brakdagflask
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
    image: 'ghcr.io/linuxserver/swag'
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    volumes:
      - '${PWD}/swag:/config'      
volumes:
  db_data:
networks:
  brakdag-network:
    driver: bridge