version: '3.3'
services:
    brakdagflask:
        build: .
        container_name: brakdagflask
        ports:
            - '8000:5000'
        image: 'brakdagflask:latest'
    nginx:
        build: 
            context: .
            dockerfile: nginx/Dockerfile
        container_name: nginx
        ports:
            - '80:80'
        image: 'nginx:latest'
    newsparse:
        build:
            context: .
            dockerfile: newsparse/Dockerfile
        container_name: newsparse
        image: 'newsparse:latest'