version: '3.3'
services:
  brakdagflask:
    build: .
    container_name: brakdagflask
    ports:
      - '8000:5000'
    image: 'brakdagflask:latest'
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: brakdag
      MYSQL_USER: brakdag
      MYSQL_PASSWORD: brakdag
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: brakdag       
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    image: 'nginx:latest'
    depends_on:
      - brakdagflask
      - db
      - phpmyadmin
  # newsparse:
  #   build:
  #     context: .
  #     dockerfile: newsparse/Dockerfile
  #   container_name: newsparse
  #   image: 'newsparse:latest'
volumes:
  db_data: